### ISSUE TITLE
suggestions for improvement

### ISSUE THREAD

**Issue by murphyk** [gaussianBP/gaussianBP.github.io#2]
Hi. I think https://gaussianbp.github.io/ is very neat, but could be improved in these easy ways:
- give the detailed equations for the variable-to-factor and factor-to-variable computations  (sec 3.4 and 3.5 of your [Future Mapping 2](https://arxiv.org/abs/1910.14139) paper). This will make the tutorial more self-contained.
- give the details of the local evidence factor for your 1d linear interpolation example. The details are in sec 4.1 of your [Future Mapping 2](https://arxiv.org/abs/1910.14139) paper, but that paper has a lot of typos. For example, it is worth explaining that, for observation y_i with latent spatial nearest neighbors x_i and x_i', the measurement function has the form 

<img src="https://render.githubusercontent.com/render/math?math=h([x_i, x_i']) =  \lambda_i y_i  +   (1-\lambda_i) y_i  ">

where

<img src="https://render.githubusercontent.com/render/math?math=\lambda_i = \frac{y_i - x_i}{x_i - x_i'} ">

If you include these details, it will make your [colab code](https://colab.research.google.com/drive/1-nrE95X4UC9FBLR0-cTnsIP_XhA_PZKW?usp=sharing#scrollTo=cpQngvFUqBLW) less mysterious.

**Comment by joeaortiz** [comment]
Hi Kevin,

Thanks for the comments and for taking the time to look through the article and code in detail!
Both suggestions are very useful and I've now included both additions in the article.

Thanks,
Joe
