### ISSUE TITLE
Why is marginalisation summation in the messages instead of integration?

### ISSUE THREAD

**Issue by danmackinlay** [gaussianBP/gaussianBP.github.io#4]
In the belief propagation algorithm we seem to be using summation to describe marginalisation, https://gaussianbp.github.io/#the-belief-propagation-algorithm which is slight confusing since we are operating on Gaussian RVs. Would it not be more natural to use integration for RVs with continuous state space, as these are?
<img width="418" alt="Screenshot 2023-06-23 at 9 30 53 am" src="https://github.com/gaussianBP/gaussianBP.github.io/assets/21740/edd988e5-1e08-4450-af2d-257fece4c6d6">

**Comment by joeaortiz** [comment]
Thanks for picking up on this, again this is another thing we could have made clearer in the article. The reason we used summation here is that in this section we were describing BP in general (not specifically the Gaussian case) and it is notationally simpler to use summations. We were also following this choice that we've seen made elsewhere including in Bishop's textbook. 

I'll add a sentence clarifying this however. As you point out it may cause some confusion. 

Thanks for your feedback!!

**Comment by danmackinlay** [comment]
@joeaortiz thank you for the response. I get the motivation.
If you are applying updates to the doc, might I also suggest that you put some parentheses in the factor message term? I know that product binds more tightly than summation, but it wouldn't hurt to disambiguate IMO.

**Comment by joeaortiz** [comment]
Thanks, I've added some clarifications based on your suggestions in the latest commit: https://github.com/gaussianBP/gaussianBP.github.io/commit/ae866dbc96f679c45750a17412cd3526779d4ff3
