### ISSUE TITLE
Accompanying workbook has non-executable or unfinished cruft at the end

### ISSUE THREAD

**Issue by danmackinlay** [gaussianBP/gaussianBP.github.io#5]
Not quite sure if this is the right place to leave this note
However, the accompanying [google colaboratory nbotebook](https://colab.research.google.com/drive/1-nrE95X4UC9FBLR0-cTnsIP_XhA_PZKW?usp=sharing&pli=1) has an error

In all the cells below [this one](https://colab.research.google.com/drive/1-nrE95X4UC9FBLR0-cTnsIP_XhA_PZKW#scrollTo=WjyI3nmpdUxM&line=1&uniqifier=1) the code raises an error.
I believe what has happened here is that there was a new example under construction but it was never completed?
In its half-finished state it is confusing.

Error is as follows

```text
---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-13-d8c1684fe834> in <module>()
      2 
      3 # Initialize variable nodes for frames with prior
----> 4 for i in range(size):
      5     for j in range(size):
      6         init = torch.FloatTensor([j, i]) + torch.normal(torch.zeros(2), prior_noise_std)

NameError: name 'size' is not defined
```

**Comment by joeaortiz** [comment]
Thanks for pointing this out and sorry for taking some time to get back on this! As you point out, those cells are the start of another example that I didn't finish off. I've removed them for now.
