### ISSUE TITLE
What Does "N^-1" Mean in Gaussian Belief Propagation?

### ISSUE THREAD

**Issue by usamic** [gaussianBP/gaussianBP.github.io#6]
Hello, I am currently reading your article titled "A Visual Introduction to Gaussian Belief Propagation."

I am somewhat confused by the notation _N<sup>-1</sup>_  mentioned in Appendix B. My interpretation suggests that this notation might be used because the outputs involve η and Λ, but since I am new to belief propagation, there may be gaps in my understanding.

Could you please clarify what _N<sup>-1</sup>_ signifies and why this notation is used? Additionally, if you could provide references to any literature where this notation is commonly used, that would be very helpful.

Lastly, I would like to express my appreciation for your excellent article.

Thank you for your time.

![Untitled](https://github.com/gaussianBP/gaussianBP.github.io/assets/91708748/764278e7-8738-4a9b-8f1f-79a55264fa3f)

**Comment by joeaortiz** [comment]
It is used to denote the Gaussian canonical parameterization (as opposed to the moments parameterization). See discussion of the two parameterizations in Sec 2.3.3.1 of this text book: https://probml.github.io/pml-book/book2.html
